Mainproject/bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]

if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Mainproject/bookstore/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<p>',views.add_to_cart,name="addtocart"),
    path('cartview', views.cartview,name="cartview"),
    path('cart_remove/<p>',views.cart_remove,name="cart_remove"),
    path('full_remove/<p>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview', views.orderview, name="orderview"),



]

Mainproject/bookstore/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('search',views.search,name="search"),

]

Mainproject/bookstore/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name="allbook"),
    path('allbooks/<p>',views.allbooks,name="allbooks"),
    path('detail/<p>',views.detail,name="detail"),
    path('reg',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
]

Mainproject/bookstore/cart/models.py
from django.db import models
from shop.models import Book
from django.contrib.auth.models import User

class Cart(models.Model):
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.book.name
    def subtotal(self):
        return self.quantity*self.book.price
class Order(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

Mainproject/bookstore/search/models.py
from django.db import models

# Create your models here.

Mainproject/bookstore/shop/models.py
from django.db import models
class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    image= models.ImageField(upload_to='shop/book', blank=True, null=True)
    price= models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

Mainproject/bookstore/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Book
from cart.models import Cart
from cart.models import Account,Order


def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.book.price
    except:
        pass


    return render(request,'cart.html',{'c':cart, 'total':total})
@login_required
def add_to_cart(request,p):
    book=Book.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,book=book)
        if(cart.quantity<cart.book.stock):
            cart.quantity+=1
        cart.save()
    except:

        cart=Cart.objects.create(book=book,user=u,quantity=1)
        cart.save()
    return redirect('cart:cartview')

def cart_remove(request,p):
    p=Book.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,book=p)
        if cart.quantity>1:
            cart.quantity-=1

            cart.save()

        else:
            cart.delete()

    except:
        pass
    return redirect('cart:cartview')


def full_remove(request, p):
    p = Book.objects.get(name=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, book=p)



        cart.delete()

    except:
        pass
    return redirect('cart:cartview')


def orderform(request):
    if (request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)


        total=0
        for i in cart:
            total+=i.quantity*i.book.price

        ac=Account.objects.get(acctnum=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:
                o=Order.objects.create(user=u,book=i.book,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                o.save()
                i.book.stock=i.book.stock-i.quantity
                i.book.save()


            cart.delete()
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'m':msg})


        else:
            msg="Insufficient Amount in User Account. You cannot place  order."
            return render(request, 'orderdetail.html', {'m': msg})
    return render(request,'orderform.html')

def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'u':u.username,'o':o})

Mainproject/bookstore/search/views.py
from django.shortcuts import render
from shop.models import Book
from django.db.models import Q
# Create your views here.
def search(request):
    q=""
    book=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            book=Book.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))

    return render(request,'search.html',{'p':book,'query':q})

Mainproject/bookstore/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Book
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allbooks(request,p):
    c=Category.objects.get(name=p)
    p=Book.objects.filter(category=c)
    return render(request, 'book.html',{'c':c,'p':p})

def detail(request,p):
    book=Book.objects.get(name=p)

    return render(request,'detail.html',{'p':book})

def register(request):
    if request.method == "POST":
        u = request.POST['u']
        p = request.POST['p']
        cp =request.POST['cp']
        e  =request.POST['e']


        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e)
            u.save()
            return redirect('shop:allbook')
        else:
            return HttpResponse("Password Not Matching")

    return render(request,'register.html')
def user_login(request):
    if request.method=="POST":
        name=request.POST['u']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)
        if user:
            login(request,user)
            return redirect('shop:allbook')
        else:
            messages.error(request,"Invalid Credentials")
    return render(request,'login.html')


@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

Mainproject/bookstore/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TinyTales</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Poppins:wght@200&family=Roboto+Slab&family=Roboto:wght@300&family=Signika+Negative&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
    <center><img src="{% static 'images/logo.jpg' %}" class="mb-2" height="100px" width="100px"</center>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TinyTales</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allbook' %}">Home</a>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allbooks' i.name %}">{{i.name}} </a></li>{% endfor %}
          </ul>
          </li>
          {% if user.is_authenticated %}
          {% if user.username != 'admin' %}
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>&nbsp;&nbsp;<sub>{{count}}<sub></sub></a>
          </li>

          <li class="nav-item">
           <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your orders</a>
          </li>
          {% endif %}

          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
          </li>
          {% else %}



         <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
          </li>
        <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}
          </ul>

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
<footer>
    <div class="footer mt-5">
    <div>
        <p><i class="fa-regular fa-copyright"></i>TinyTales pvt ltd.All Rights Reserved.</p>
    </div>
</div>
</footer>
</body>
</html>

Mainproject/bookstore/templates/book.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4" style="margin-bottom:60px;">
    <img src="{{c.image.url}}" width="100%" height="450px">
</div>

<div class="container-fluid mt-1" style="margin-bottom:60px;">
    <h3 class="text-center fw-bold pb-3"> {{c.name}}</h3>
    <p style="line-height:2;text-align:justify;"> {{c.desc}} </p>
</div>
<div class="container-fluid mt-1" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4 mb-4">
            <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%;">
  <div class="card-body" >
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5 class="text-center">{{i.price}}</h5>
    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:38%; bottom:30%;">DETAILS</a>
  </div>
</div>

        </div>{% endfor %}
    </div>
</div>
{% endblock %}

Mainproject/bookstore/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not c %}
<div class="container-fluid mt-3">
    <h3 class="text-center">Cart is empty</h3>
    <h5 class="text-center text-success"><a href="{% url 'shop:allbook' %}">Continue Shopping</a></h5>
</div>

{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">SHOPPING CART</h4>

    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr><th colspan="5" class="text-center">CART ITEMS</th></tr>
            {% for i in c %}
            <tr>
                <td><img src="{{i.book.image.url}}" height="150px" width="150px"></td>
                <td><b>{{i.book.name}}</b></td>
                <td><b>Book id:{{i.book.id}}</b><br>
                   <b>Unit Price:{{i.book.price}}</b><br>
                <b>Quantity:{{i.quantity}}*{{i.book.price}}</b></td>


                <td><b>Subtotal:{{i.subtotal}}</b></td>
                <td>
                    {% if i.quantity < i.book.stock %}
                <a href="{% url 'cart:addtocart' i.book.name%}"><i class="fa-solid fa-circle-plus"></i></a>
                <a href="{% url 'cart:cart_remove' i.book.name%}"><i class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.book.name%}"><i class="fa-solid fa-trash-can"></i></a></td>
{% else %}
                <a href="{% url 'cart:cart_remove' i.book.name%}"><i class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.book.name%}"><i class="fa-solid fa-trash-can"></i></a></td>
            </tr>
            {% endif %}
{% endfor %}
        </table>
    </div>

    <div class="col-sm-4" style="position:relative">
        <table class="table table-bordered">
        <tr><th colspan="4">CHECK OUT</th></tr>
            <tr  class="text-center"><td><b>TOTAL: <span class="text-danger"> {{total}}</span></b></td></tr>
        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-warning text-dark"><b>Place Order</b></a>
        <a href="{% url 'shop:allbook' %}" class="btn btn-warning text-dark" style="position:absolute;right:10px;"><b>Continue Shopping</b></a>
    </div>
</div>
</div>
{% endif %}
  {% endblock %}

Mainproject/bookstore/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    p
    {color:#000066;
    }
</style>
<div>
   <image src="{% static 'images/img.png' %}"  height="400px" width="100%"></image>

<!--    <center>-->
<!--    <image src="{% static 'images/giffybest.gif' %}"  height="200px" width="20%"></image></center>-->

<div class="container-fluid mt-4" style="margin-bottom:50px;">
    <h3 class="text-center"> Let's Explore....</h3>
    <p style="line-height:1.6;text-align:justify;"> "Embark on a Literary Wonderland with Our Extraordinary Kids' Book Collections! At our online store, we've carefully curated enchanting assortments of stories that cater to every young reader's imagination. From captivating bedtime tales that whisk them away to dreamland, to educational gems that make learning an exciting adventure – our collections are a treasure trove of literary delights.Every book in our collection is not just a story; it's a key to unlocking the boundless potential within each child. Fuel their curiosity, ignite their creativity, and build a lifelong love for reading with our meticulously crafted kids' book collections. Explore the magic today!"</p>
      <center>
    <image src="{% static 'images/giffybest.gif' %}"  height="300px" width="30%"></image></center>
</div>
<div class="container-fluid mt-2" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4 mb-4">
            <div class="card" style="width: 28rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>

    <a href="{% url 'shop:allbooks' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">Click here</a>
  </div>
</div>

        </div>{% endfor %}
    </div>
</div>


{% endblock %}

Mainproject/bookstore/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4" style="margin-bottom:60px;margin-left:250px;">
    <div class="container">
    <div class="row">
        <div class="col-sm-4"><img src="{{p.image.url}}" height="370px" width="370px"></div>
        <div class="col-sm-5">
            <h4>{{p.name}}</h4>
            <h5 class="mt-2">{{p.price}}</h5>
            {{p.stock}}
            <p class="mt-2" style="text-indent:20px;line-height:1.8;text-align:justify">{{p.desc}}</p>

            {% if user.is_superuser == False %}


            {% if p.stock <= 0%}
            <h4>Out of Stock</h4>
            {% else %}

            <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-secondary mt-4">Add To Cart</a></h4>
            {% endif %}

            {% else %}
            {% if p.stock <= 0%}
            <h4>Out of Stock</h4>

            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>
            {% else %}
             <h4>Product in Stock</h4>
            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>


            {% endif %}
                {% endif %}
        </div>
    </div></div>

  {% endblock %}

Mainproject/bookstore/templates/login.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
<h2>LOGIN PAGE</h2>
    <form method="POST">
 {% csrf_token %}
 <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
    </div>
    <div  class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter the password">
    </div>
        <div  class="mb-3">
         <input type="submit" class="form-control">
</div>
    </form>
{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
 {% endfor %}
 {% endif %}
</div>
{% endblock %}

Mainproject/bookstore/templates/orderdetail.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
  <center>
     <h3 class="text-center text-secondary">{{m}}</h3>
     <h5 class="text-center text-success">Thank You.....</h5>
     <h6><a href="% url 'shop:allbook' %}">Continue Shopping</a></h6>
   </center>
</div>
{% endblock %}

Mainproject/bookstore/templates/orderform.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
<h2>Enter Order Details</h2>
    <form method="POST">
 {% csrf_token %}
 <div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the Address">
    </div>
        <div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="text" class="form-control" name="p" placeholder="Enter the Phone">
    </div>
        <div class="mb-3">
  <label class="form-label">Account Number</label>
  <input type="text" class="form-control" name="n" placeholder="Enter the Account Number">
    </div>

        <div  class="mb-3">
         <input type="submit" class="form-control">
</div>
    </form>
{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
 {% endfor %}
 {% endif %}
</div>
{% endblock %}

Mainproject/bookstore/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
    <h6>Customer Name:{{u}}</h6>

    <div class="row">
        <h4 style="color:red">Order Details</h4>
        {% for i in o %}
        <div class="col-sm-3 my-3 py-2 border border-1 border-secondary">
           <center> <img src="{{i.book.image.url}}" height="150px" width="150px"></center>
        </div>
        <div class="col-sm-7 my-3 pe-3  border border-1 border-secondary">
            <b> Delivery Address:{{i.address}}</b><br>
            <b> Customer Phone:{{i.phone}}</b><br>
            <b> Book name:{{i.book.name}}</b><br>
            <b> Price Address:{{i.book.price}}</b><br>
            <b> No of items:{{i.no_of_items}}</b><br>
            <b> Ordered On:{{i.date_ordered}}</b><br>
            <b> DeliveryStatus:<span class="text-danger">{{i.delivery_status}}</span></b><br>
        </div>


    {% endfor %}
        </div>
</div>
{% endblock %}

Mainproject/bookstore/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">

 <h2>REGISTER HERE</h2>
    <form method="POST">
 {% csrf_token %}
 <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control"  name="u" placeholder="enter the username">
</div>
     <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="enter the password">
</div>
     <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter the confirm password">
</div>
<div class="mb-3">
  <label  class="form-label">email</label>
  <input type="email" class="form-control" name="e" placeholder="enter the email">
</div>

    <div class="mb-3">

    <input type="submit" class="form-control">
    </div>

{% endblock %}

Mainproject/bookstore/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="text-center"><h4>You Have Searched for <span class="text-success fw-bolder">{{query}}</span></h4></div>
</center>
<div class="container mt-2 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card mb-4" style="width:27rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%;">
  <div class="card-body" >
    <h5 class="card-title text-center">{{i.name}}</h5>
      <h5 class="text-center">{{i.price}}</h5>
    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a>
  </div>
</div>

        </div>
{% empty %}
        <h4 class="text-center text-danger">No Search Results Found</h4>
        {% endfor %}
    </div>
</div>



{% endblock %}